#!/usr/bin/env python3
"""file_to_c - convert a binary file into a C array (DinoPad-owned replacement
for the upstream file_to_c host utility referenced by dino-recomp's CMake).

Usage: file_to_c.py <input.bin> <symbol> <output.c> <output.h>
"""
import sys


def main() -> int:
    if len(sys.argv) != 5:
        print(__doc__, file=sys.stderr)
        return 2
    src, symbol, out_c, out_h = sys.argv[1:]
    data = open(src, "rb").read()
    n = len(data)
    with open(out_h, "w") as fh:
        fh.write("// Generated by DinoPad tools/file_to_c.py. Do not edit.\n")
        fh.write(f"extern const unsigned char {symbol}[{n}];\n")
    with open(out_c, "w") as fh:
        fh.write("// Generated by DinoPad tools/file_to_c.py. Do not edit.\n")
        fh.write(f'#include "{out_h.rsplit("/", 1)[-1]}"\n')
        fh.write(f"const unsigned char {symbol}[{n}] = {{\n")
        for i in range(0, n, 12):
            chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
            fh.write(f"{chunk},\n")
        fh.write("};\n")
    print(f"{symbol}: {n} bytes -> {out_c}, {out_h}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
