#!/usr/bin/env python3
"""Generate a typed static symbol table for OfflineModRecomp C output."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DECL_RE = re.compile(
    r"^RECOMP_FUNC void mod_func_(\d+)\(uint8_t\* rdram, recomp_context\* ctx\);$",
    re.MULTILINE,
)
DEF_RE = re.compile(
    r"^RECOMP_FUNC void mod_func_(\d+)\(uint8_t\* rdram, recomp_context\* ctx\) \{$",
    re.MULTILINE,
)


def one_count(pattern: str, source: str, label: str) -> int:
    match = re.search(pattern, source, re.MULTILINE)
    if match is None:
        raise ValueError(f"missing {label} declaration")
    return int(match.group(1))


def render(source_path: Path) -> tuple[str, str]:
    source = source_path.read_text(encoding="utf-8")
    declarations = [int(value) for value in DECL_RE.findall(source)]
    definitions = [int(value) for value in DEF_RE.findall(source)]
    expected = list(range(len(declarations)))
    if declarations != expected:
        raise ValueError("mod function declarations are not contiguous from zero")
    if definitions != expected:
        raise ValueError("mod function definitions do not match declarations")

    imports = one_count(
        r"^RECOMP_EXPORT recomp_func_t\* imported_funcs\[(\d+)\]", source, "import table"
    )
    references = one_count(
        r"^RECOMP_EXPORT recomp_func_t\* reference_symbol_funcs\[(\d+)\]",
        source,
        "reference table",
    )
    sections = one_count(
        r"^RECOMP_EXPORT int32_t section_addresses\[(\d+)\]", source, "section table"
    )

    header = f"""// Generated by tools/generate_static_mod_exports.py. Do not edit.
#ifndef DINOPAD_STATIC_MOD_EXPORTS_H
#define DINOPAD_STATIC_MOD_EXPORTS_H

#include <stddef.h>
#include <stdint.h>
#include "recomp.h"

#ifdef __cplusplus
extern "C" {{
#endif

enum {{
    DINOPAD_MOD_FUNCTION_COUNT = {len(declarations)},
    DINOPAD_MOD_IMPORT_COUNT = {imports},
    DINOPAD_MOD_REFERENCE_COUNT = {references},
    DINOPAD_MOD_SECTION_COUNT = {sections},
}};

extern uint32_t dinopad_mod_recomp_api_version;
extern recomp_func_t* dinopad_mod_imported_funcs[DINOPAD_MOD_IMPORT_COUNT];
extern recomp_func_t* dinopad_mod_reference_symbol_funcs[DINOPAD_MOD_REFERENCE_COUNT];
extern uint32_t dinopad_mod_base_event_index;
extern void (*dinopad_mod_recomp_trigger_event)(uint8_t*, recomp_context*, uint32_t);
extern recomp_func_t* (*dinopad_mod_get_function)(int32_t);
extern void (*dinopad_mod_cop0_status_write)(recomp_context*, gpr);
extern gpr (*dinopad_mod_cop0_status_read)(recomp_context*);
extern void (*dinopad_mod_switch_error)(const char*, uint32_t, uint32_t);
extern void (*dinopad_mod_do_break)(uint32_t);
extern int32_t* dinopad_mod_reference_section_addresses;
extern int32_t dinopad_mod_section_addresses[DINOPAD_MOD_SECTION_COUNT];
extern recomp_func_t* const dinopad_mod_functions[DINOPAD_MOD_FUNCTION_COUNT];

#ifdef __cplusplus
}}
#endif

#endif
"""

    declarations_text = "\n".join(
        f"void mod_func_{index}(uint8_t* rdram, recomp_context* ctx);"
        for index in declarations
    )
    table_text = ",\n".join(f"    mod_func_{index}" for index in declarations)
    table = f"""// Generated by tools/generate_static_mod_exports.py. Do not edit.
#include "dinomod_static_exports.h"

{declarations_text}

recomp_func_t* const dinopad_mod_functions[DINOPAD_MOD_FUNCTION_COUNT] = {{
{table_text}
}};
"""
    return header, table


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("header", type=Path)
    parser.add_argument("table", type=Path)
    args = parser.parse_args()

    header, table = render(args.source)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.table.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(header, encoding="utf-8")
    args.table.write_text(table, encoding="utf-8")
    function_count = len(DECL_RE.findall(args.source.read_text(encoding="utf-8")))
    print(f"static-mod-exports: functions={function_count} generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
